config/routes.rb
Rails.application.routes.draw do
  get 'profiles'  => 'profiles#index'

  get 'profiles/:id' => 'profiles#show', as: :profile


  resources :relationships

  resources :tweets do
    resource :likes
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :message, presence: true, length: { maximum: 140, too_long: 'A tweet is only 140 characters max.'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_relationships, source: :user

  has_many :likes
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :locations, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
      @tweet.likes.where(user_id: current_user.id).first_or_create

      respond_to do |format|
        format.html { redirect_to request.referrer }
      end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @friend = User.find(params[:friend_id])
    @relationship = current_user.relationships.build(friend_id: @friend.id)

    if @relationship.save
      flash[:notice] = "You're not following #{@friend.username}."
      redirect_to profile_path(@friend.id)
    else

      flash[:notice] = "Unable to follow"
      redirect_to profile_path(@friend.id)
    end
end

def destroy
  @relationship = current_user.relationships.find(params[:id])
  @relationship.destroy
  # @friend = User.find(params[:id])

  flash[:notice] = "No longer stalking"
  redirect_to profile_path(current_user.id)
end

private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterette</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-info' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>

  <%= link_to user.username, profile_path(user) %> <br>

<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-4">
  <h3><%= @user.name %></h3>
  <h5><%= @user.username %></h5>
  <h5><p><%= @user.bio %></p></h5>
  <h5><%= @user.location %></h5>
  <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <%= @user.relationships.count %> Following
  <br />
  <% @user.relationships.each do |relationship| %>
    <%=link_to relationship.friend.name, profile_path(relationship.friend) %>
  <%end%>
  <br />
  <br />
  <%= pluralize(@user.inverse_relationships.count, "Follower") %>.
  <br />
  <% @user.inverse_friends.each do |friend| %>
    <%=link_to friend.name, profile_path(friend) %> <br />
  <%end%>
  </div>

  <div class= "col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
          <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
          <br />
          <br />
          <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br />
<br />
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
  <% else %>
    <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
  <% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete %>
<% else %>
  <%= link_to "Like", tweet_likes_path(@tweet), method: :post %>
<% end %>

<%= @tweet.likes.count %>

Liked by:
<% @tweet.likes.each do |like| %>
  <br>
  <%= like.user.username %>
  <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :tweet_message %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<%= image_tag current_user.avatar.url, size: 200 %>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td>@<%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-info' %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= render 'shared/likes' %>

<br>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>